# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Lint check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - name: Install Flutter
      #   uses: britannio/action-install-flutter@v1.1

      # - name: Install dependencies
      #   run: flutter pub get

      # # Consider passing '--fatal-infos' for slightly stricter analysis.
      # - name: Analyze project source
      #   run: flutter analyze
