name: Mark PR Ready for Review

on:
  pull_request:
    branches:   
      - main 
  check_suite:
    types: [completed]

jobs:
  mark-ready-for-review:
    name: Mark PR Ready for Review
    runs-on: ubuntu-latest
    permissions:
      checks: read

    # if: github.event.check_suite.conclusion == 'success' && github.event.check_suite.pull_requests[0]
    
    steps:
      - name: Mark PR as Ready for Review
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(`Workflow triggered. Congrats!!`);
